# Generated by Django 6.0.2 on 2026-02-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_seed_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='nok_relationship',
            field=models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Uncle', 'Uncle'), ('Aunt', 'Aunt'), ('Gudian', 'Gudian')], max_length=50),
        ),
    ]
