# Generated by Django 6.0.2 on 2026-02-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_nok_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='clinics',
        ),
    ]
