# Generated by Django 6.0.2 on 2026-02-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_staff_clinics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='phone',
        ),
    ]
