# Generated by Django 6.0.2 on 2026-02-24 08:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_remove_staff_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='nok_phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+256XXXXXXXXX' (total 13 characters).", regex='^\\+256\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='nok_relationship',
            field=models.CharField(max_length=50),
        ),
    ]
