# Generated by Django 6.0.2 on 2026-02-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_staff_nok_phone_alter_staff_nok_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='nok_relationship',
            field=models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Uncle', 'Uncle')], max_length=50),
        ),
    ]
