# Generated by Django 6.0.2 on 2026-02-24 09:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_staff_nok_relationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dutyroster',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dutyroster',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='dutyroster',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='dutyroster',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='support_role',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='technical_role',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+256XXXXXXXXX' (total 13 characters).", regex='^\\+256\\d{9}$')])),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='staff_profile_pics/')),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('employment_type', models.CharField(choices=[('technical', 'Technical'), ('support', 'Support')], max_length=10)),
                ('role', models.CharField(choices=[('physician', 'Physician/Doctor'), ('specialist', 'Specialist'), ('nurse', 'Nurse'), ('nurse_practitioner', 'Nurse Practitioner'), ('physician_assistant', 'Physician Assistant'), ('medical_assistant', 'Medical Assistant'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Lab Technician'), ('radiology_technician', 'Radiology Technician'), ('dietitian', 'Dietitian/Nutritionist'), ('social_worker', 'Social Worker/Counselor'), ('clinic_manager', 'Clinic Manager/Administrator'), ('receptionist', 'Receptionist/Front Desk'), ('billing_specialist', 'Billing & Insurance Specialist'), ('records_clerk', 'Medical Records Clerk'), ('it_support', 'IT Support Staff'), ('maintenance', 'Cleaning & Maintenance Staff')], max_length=30)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('next_of_kin', models.CharField(max_length=100)),
                ('nok_relationship', models.CharField(max_length=50)),
                ('nok_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+256XXXXXXXXX' (total 13 characters).", regex='^\\+256\\d{9}$')])),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('duty_status', models.CharField(choices=[('on_duty', 'On Duty'), ('on_leave', 'On Leave'), ('off_duty', 'Off Duty')], default='on_duty', max_length=10)),
                ('owner', models.ForeignKey(limit_choices_to={'profile__user_type': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ClinicStaffAssignment',
        ),
        migrations.DeleteModel(
            name='DutyRoster',
        ),
        migrations.DeleteModel(
            name='SupportStaff',
        ),
        migrations.DeleteModel(
            name='TechnicalStaff',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
