# Generated by Django 6.0.2 on 2026-02-21 11:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('order', models.PositiveSmallIntegerField(help_text='1=Monday, 7=Sunday', unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='clinics.district')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'district')},
            },
        ),
        migrations.CreateModel(
            name='Subcounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcounties', to='clinics.county')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'county')},
            },
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('subcounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parishes', to='clinics.subcounty')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'subcounty')},
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='clinics.parish')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'parish')},
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slogan', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic_logos/')),
                ('phone', models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, help_text='Clinic contact email', max_length=254, null=True)),
                ('website', models.URLField(blank=True, help_text='Clinic website URL', null=True)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact number', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('description', models.TextField(blank=True, help_text='About the clinic')),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('established_date', models.DateField(blank=True, help_text='Date clinic was established', null=True)),
                ('registration_date', models.DateField()),
                ('licence_expiry_date', models.DateField()),
                ('licensing_body', models.CharField(choices=[('UMDPC', 'Uganda Medical and Dental Practitioners Council (UMDPC)'), ('AHPC', 'Allied Health Professionals Council (AHPC)'), ('UNMC', 'Uganda Nurses and Midwives Council (UNMC)'), ('Pharmacy', 'Pharmacy Council of Uganda'), ('Others', 'Others')], max_length=50)),
                ('registration_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('supervisor_title', models.CharField(choices=[('MD', 'MD'), ('MCO', 'MCO'), ('EN', 'EN'), ('RN', 'RN'), ('BSN', 'BSN'), ('Others', 'Others')], max_length=64)),
                ('supervisor', models.CharField(max_length=200)),
                ('is_main_clinic', models.BooleanField(default=False, help_text='Mark if this is the primary clinic')),
                ('has_pharmacy', models.BooleanField(default=False, help_text='On-site pharmacy?')),
                ('has_lab', models.BooleanField(default=False, help_text='On-site laboratory?')),
                ('operation_status', models.CharField(choices=[('operating', 'Operating'), ('not_operating', 'Not Operating')], db_index=True, default='operating', max_length=20)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to=settings.AUTH_USER_MODEL)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinics', to='clinics.county')),
                ('operation_days', models.ManyToManyField(related_name='clinics', to='clinics.day')),
                ('departments', models.ManyToManyField(related_name='clinics', to='clinics.department')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinics', to='clinics.district')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinics', to='clinics.parish')),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinics', to='clinics.subcounty')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinics', to='clinics.village')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'supervisor'), name='unique_supervisor_per_owner')],
            },
        ),
    ]
