# Generated by Django 6.0.2 on 2026-02-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_auto_20260221_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='has_lab',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='has_pharmacy',
        ),
    ]
