# Generated by Django 6.0.2 on 2026-02-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_remove_clinic_has_lab_remove_clinic_has_pharmacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
