# Generated by Django 6.0.2 on 2026-02-21 16:42

import clinics.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_alter_clinic_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=clinics.utils.logo_upload_to),
        ),
    ]
