# Generated by Django 6.0.2 on 2026-02-23 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_alter_clinic_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact number', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+256XXXXXXXXX' (total 13 characters).", regex='^\\+256\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone',
            field=models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+256XXXXXXXXX' (total 13 characters).", regex='^\\+256\\d{9}$')]),
        ),
    ]
