# Generated by Django 6.0.3 on 2026-03-06 19:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0007_alter_clinic_emergency_contact_alter_clinic_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Drug category',
                'verbose_name_plural': 'Drug categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Formulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SaleUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StorageCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(db_index=True, max_length=200)),
                ('generic_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('reorder_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reorder level')),
                ('stock_target', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Stock target')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sale price')),
                ('discontinued', models.BooleanField(default=False, help_text='Item is discontinued')),
                ('pause_stocking', models.BooleanField(default=False, help_text='Temporarily pause ordering/stocking')),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete flag; inactive items are hidden')),
                ('entered_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='clinics.clinic')),
                ('drug_categories', models.ManyToManyField(blank=True, related_name='items', to='inventory.drugcategory')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_entered', to=settings.AUTH_USER_MODEL)),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.formulation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_updated', to=settings.AUTH_USER_MODEL)),
                ('sale_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.saleunit')),
                ('storage_condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.storagecondition')),
            ],
            options={
                'verbose_name': 'Inventory item',
                'verbose_name_plural': 'Inventory items',
                'ordering': ['brand_name'],
            },
        ),
    ]
